=== evolvedbinary/elemental/schema/controller-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Elemental
    Copyright (C) 2024, Evolved Binary Ltd

    admin@evolvedbinary.com
    https://www.evolvedbinary.com | https://www.elemental.xyz

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; version 2.1.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

    NOTE: Parts of this file contain code from 'The eXist-db Authors'.
          The original license header is included below.

    =====================================================================

    eXist-db Open Source Native XML Database
    Copyright (C) 2001 The eXist-db Authors

    info@exist-db.org
    http://www.exist-db.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
           xmlns:exist="http://exist.sourceforge.net/NS/exist"
           elementFormDefault="qualified"
           targetNamespace="http://exist.sourceforge.net/NS/exist"
           version="1.0.0">
  <xs:element name="configuration">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="exist:forward"/>
        <xs:element ref="exist:root"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="forward">
    <xs:complexType>
      <xs:attribute name="pattern" use="required" type="xs:string"/>
      <xs:attribute name="servlet" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="root">
    <xs:complexType>
      <xs:attribute name="server-name" use="optional" type="xs:string"/>
      <xs:attribute name="path" use="required" type="xs:anyURI"/>
      <xs:attribute name="pattern" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== evolvedbinary/elemental/exist-jetty-config/src/main/resources/webapp/WEB-INF/controller-config.xml
<!--
  ++ Base configuration for eXist's URL rewriting. This file defines
  ++ all basic path mappings. A path can be mapped to a servlet or
  ++ the root of a directory or collection hierarchy.
  ++
  ++ The order of elements within this configuration file is significant.
-->
<configuration xmlns="http://exist.sourceforge.net/NS/exist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://exist.sourceforge.net/NS/exist file:../../schema/controller-config.xsd">
  
  <!-- Webstart servlet -->
  <forward pattern="/webstart" servlet="jnlp"/>
  
  <!-- XMLRPC servlet -->
  <forward pattern="/xmlrpc" servlet="org.exist.xmlrpc.RpcServlet"/>
  
  <!-- REST interface -->
  <forward pattern="/(rest|servlet)/" servlet="EXistServlet"/>
  
  <!-- WebDAV interface -->
  <forward pattern="/webdav/" servlet="milton"/>
  
  <!-- RESTXQ -->
  <forward pattern="/restxq/" servlet="RestXqServlet"/>
  
  <!-- Scale images on the fly and cache the output. -->
  <!-- 
  <forward pattern="/images" servlet="ScaleImageJAI"/>
  -->
  
  <!-- The JMX status servlet used to monitor the db -->
  <forward pattern="/status" servlet="JMXServlet"/>
  
  <!-- HTTP requests to /apps are mapped onto the database path /db/apps -->
  <root pattern="/apps" path="xmldb:exist:///db/apps"/>
  
  <!--
    ++ The default fallback web application is served from the
    ++ /etc/webapp directory on the filesystem. 
  -->
  
  <root pattern=".*" path="/"/>
  
  <!-- 
    ++ To redirect requests based on the server name (i.e. www.example.com)
  	++ to a specific collection within the database, comment out the previous
  	++ root line and uncomment the block below with the server-name
  	++ attribute.
    -->
  
  <!-- 
    <root server-name="site1.example.com" pattern="/*" path="xmldb:exist:///db/org/site1/"/>
    <root server-name="site2.example.com" pattern="/*" path="xmldb:exist:///db/org/site2/"/>
    <root server-name="site3.example.com" pattern="/*" path="xmldb:exist:///db/org/site3/"/>
    <root server-name="localhost" pattern=".*" path="/"/>
    <root server-name="site4.example.com" pattern=".*" path="/"/>
    -->
  
  <!-- 
      ++ The following alternative configuration assumes that the main webapp
      ++ is stored in the database. However, the contents of the /etc/webapp directory
      ++ will still be accessible with a /fs prefix in the path.
  -->
  <!--
    <root pattern="/fs" path="/"/>
    <root pattern=".*" path="xmldb:exist:///db/www"/>
  -->
  
  <!--
      ++ Order is important. The following forward rule for XQuery resources has 
      ++ to be last in this document. Otherwise, all XQuery files would be immediately 
      ++ forwarded to the XQueryServlet without ever going through controllers.
  -->
  <forward pattern=".*\.(xq|xql|xqy|xquery)$" servlet="XQueryServlet"/>
  
</configuration>
